### ISSUE TITLE
app\views\student\_form.php#student-identify(81): inep_id

### ISSUE THREAD

**Issue by ipti** [ipti/tag#17]
Exibir o campo inep_id da entidade aluno na tela, somente para leitura.

**Comment by franciscocabral** [comment]
Corrigido. https://github.com/ipti/tag/commit/18f23cc3814013112c49879710b324a3213304ab

**Comment by franciscocabral** [comment]
Corrigido. https://github.com/ipti/tag/commit/fe26033f2ce2adbe7468456200552fbb1856c6dd
