### ISSUE TITLE
app\controllers\ClassroomController.php#classroomDisciplineLabelArray(220)

### ISSUE THREAD

**Issue by ruanceli** [ipti/tag#25]
A disciplina "**outras**" precisa ser distrinchada em todas as variações possíveis de disciplinas que se encaixam nessa descrição a exemplo: Sociedade e Cultura, Redação.
Inseri na tabela de disciplinas mais referências para que na hora da frequência e do quadro de horário possa ser feito o controle separado dessas disciplinas que no educacenso são chamadas de "**outras**"

![image](https://cloud.githubusercontent.com/assets/1492822/9355845/0da402bc-4653-11e5-9450-baebff2309cf.png)

**Comment by franciscocabral** [comment]
Já existem as disciplinas citadas.
![captura de tela de 2015-08-21 10 21 33](https://cloud.githubusercontent.com/assets/4059355/9409140/8c239d68-47ee-11e5-994c-9565c5385c94.png)
![captura de tela de 2015-08-21 10 21 41](https://cloud.githubusercontent.com/assets/4059355/9409141/8c23ec3c-47ee-11e5-8c0b-14c4a932aae3.png)

**Comment by ruanceli** [comment]
Não seria o caso de renomear, podemos manter esses nomes. Quanto a opção "outras disciplinas" vamos manter por causa da retrocompatibilidade no momento da importação. Anexe aqui o script de inserção dessas novas disciplinas, no banco de produção elas ainda não existem.

**Comment by franciscocabral** [comment]
Só existe uma nova disciplina, que é Redação. A outra já existe no edcenso.
```sql
INSERT INTO `edcenso_discipline` (`id`, `name`) VALUES ('10001', 'Redação');
```
