### ISSUE TITLE
Nova => Sincronização

### ISSUE THREAD

**Issue by ipti** [ipti/tag#3]
Desenvolver versão nova da funcionalidade de sincronização

**Comment by franciscocabral** [comment]
Já esta pronto no Master. Em processo de teste com os bancos de produção.
https://github.com/ipti/tag/commit/cf0c09af20468dfd6f803fad8d37b32d50f34925

**Comment by franciscocabral** [comment]
Testado com os bancos de produção. Corrigido problema que apresentou quando haviam crianças transferidas. 
https://github.com/ipti/tag/commit/e47cd3ff54a3a9995ff3130ad3bdad31e193b888
