### ISSUE TITLE
Nova => Calendário Escolar

### ISSUE THREAD

**Issue by ipti** [ipti/tag#6]
Criar funcionalidade que auxilie a estruturação, organização e o planejamento do calendário escolar de maneira detalhada e personalizável, facilitando o gerenciamento da atividades didático-pedagógicas.

**Comment by franciscocabral** [comment]
Concluído. 
https://github.com/ipti/tag/commit/091f9b5860af6f2c8e8f97c5c6a8bdaa5e3f44b2
